// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicGrabber.Modules.Quota.Infrastructure.Adapters.Persistence;

#nullable disable

namespace MusicGrabber.Modules.Quota.Infrastructure.Migrations
{
    [DbContext(typeof(QuotaDbContext))]
    partial class QuotaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MusicGrabber.Modules.Quota.Domain.UserQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentThreshold")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEmailSentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastEmailThreshold")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("QuotaBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserQuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
